LandingPage/Models/CMSViewModel/CMSViewModels.cs
using DBModels;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using LandingPage.Models.CMSDetailsViewModels;

namespace LandingPage.Models.CMSViewModels
{
    public class CMSViewModels
    {
        [Display(Name = "Id")]
        public int Id { get; set; }
        [Display(Name = "Nume")]
        public String Name { get; set; }
        [Display(Name = "Menu Item")]
        public int MenuItemId { get; set; }
        [Display(Name = "Tip HTML")]
        public int HtmlType { get; set; }
        [Display(Name = "Continut")]
        public String Content { get; set; }

        public IFormFile FileUploadId { get; set; }
        public String ContentId { get; set; }
        public String TextAreaId { get; set; }
        public String HtmlEditorId { get; set; }


        public List<LandingPage.Models.CMSDetailsViewModels.CMSDetailsViewModels> CMSDetails;


        public static explicit operator CMSViewModels(CMS model)
        {
            return new CMSViewModels
            {
                Id = model.Id,
                Name = model.Name,
                MenuItemId = model.MenuItemId,
                HtmlType = model.HtmlType,
                Content = model.Content,
                ContentId = model.Content,
                TextAreaId = model.Content,
                HtmlEditorId = model.Content
            };

        }

        public CMS Transform(CMSViewModels model)
        {
            return new CMS
            {
                Id = model.Id,
                Name = model.Name,
                MenuItemId = model.MenuItemId,
                HtmlType = model.HtmlType,
                Content = model.Content
            };
        }
    }
}

LandingPage/Areas/Admin/Controllers/CMSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DBModels;
using LandingPage.Models.CMSViewModels;
using Service;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using test;
using Microsoft.AspNetCore.Authorization;

namespace LandingPage.Areas.Admin.Controllers
{
    [Area("admin")]
    [Authorize]
    public class CMSController : Controller
    {
        private IHostingEnvironment _hostingEnvironment;

        public CMSController(IHostingEnvironment emv)
        {
            _hostingEnvironment = emv;
        }

        [Route("admin/cms/getall")]
        public JsonResult GetAll()
        {
            var all = new CMSManager().GetAll();
            return Json(new { data = all });
        }
        [Route("admin/cms")]
        public IActionResult Index()
        {
            var all = new CMSManager().GetAll();
            return View(all);
        }



        [Route("admin/cms/deleteItem")]
        public JsonResult DeleteItem(int ItemId)
        {
            var _cmsItemManager = new CMSManager();
            var item = _cmsItemManager.GetById(ItemId);
            if (item.Id > 0)
            {
                _cmsItemManager.Delete(ItemId);

                return Json(true);
            }
            else
                return Json(false);
        }

        [Route("admin/cms/createItem")]
        [HttpGet]
        public IActionResult Create(int id)

        {
            ViewBag.MenuItems = new SelectList(new MenuItemManager().GetAll(), "ItemId", "Name");
            ViewBag.HtmlTypes = new SelectList(new HtmlTypesManager().GetAll(), "Id", "Name");

            var viewModel = new CMSViewModels();
            if (id > 0)
            {
                viewModel = (CMSViewModels)(new CMSManager().GetById(id));
            }

            return View(viewModel);

        }
        [Route("admin/cms/createItem")]
        [HttpPost]
         public async Task<IActionResult> Create(CMSViewModels item, IFormFile FileUploadId)
        {
            var content = "";
            if (item.HtmlType == 1)
            {
                content = item.ContentId;
            }
            else
                if (item.HtmlType == 2)
            {
                content = item.TextAreaId;
            }
            else

                if (item.HtmlType == 3)
            {
                content = item.HtmlEditorId;
            }
            else
            {
                if (item.FileUploadId != null)
            {
                    var filename = item.FileUploadId.FileName;
                    var path = Path.Combine(_hostingEnvironment.WebRootPath+"\\siteimages", filename);
                    var relpath = "/siteimages/"+filename;

                    content = relpath;
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await item.FileUploadId.CopyToAsync(stream);
                    }
                }
            }
           ViewBag.MenuItems = new SelectList(new MenuItemManager().GetAll(), "ItemId", "Name");
           ViewBag.HtmlTypes = new SelectList(new HtmlTypesManager().GetAll(), "Id", "Name");
            item.Content = content;

            if (ModelState.IsValid)
            {
                if (item.Id > 0)
                {
                    if (string.IsNullOrWhiteSpace(item.Content))
                    {
                        var oldItem = new CMSManager().GetById(item.Id);
                        item.Content = oldItem.Content;
                    }
                    new CMSManager().Update(new CMSViewModels().Transform(item));
                }
            else
                new CMSManager().Create(new CMSViewModels().Transform(item));

                return RedirectToAction("Index");
            }
            return View(item);
        }
        
    }
}

LandingPage/Areas/Admin/Views/CMS/Create.cshtml
@model LandingPage.Models.CMSViewModels.CMSViewModels

@{
    ViewData["Title"] = "View";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var title = Model.Id > 0 ? "Editare" : "Creare";
}
<head>

    <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>    
</head>

<h2>@title</h2>

<h4>CMSViewModels</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data" asp-controller="CMS">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MenuItemId" class="control-label"></label>
                <select asp-for="MenuItemId" class="form-control" asp-items="ViewBag.MenuItems"></select>
                <span asp-validation-for="MenuItemId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HtmlType" class="control-label"></label>
                <select asp-for="HtmlType" class="form-control" id="HtmlTypeDDL" asp-items="ViewBag.HtmlTypes"></select>

                <span asp-validation-for="HtmlType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" id="ContentId"  name="ContentId" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <textarea rows="4" cols="50" id="TextAreaId" name="TextAreaId" asp-for="TextAreaId">
            </textarea>

            </div>
            <div class="form-group">
                <textarea id="HtmlEditorId" name="HtmlEditorId" asp-for="HtmlEditorId">
            </textarea>
            </div>
            <div class="form-group">
                <img width ="200" src="@Model.Content" alt="">
                <input type="file" name="FileUploadId" id="FileUploadId" asp-for="FileUploadId" />
            </div>
            <div class="form-group">
                <input type="submit" value="@title" class="btn btn-default" />
            </div>

        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script src="~/js/jquery.js"></script>

<script type="text/javascript" >$(document).ready(function () {
  
    
     CompleteValues();
 
    $("#HtmlTypeDDL").change(function () {
        CompleteValues();
           
            });
    
    
    }); 

    function CompleteValues() {
        var HtmlTypeDDV = $("#HtmlTypeDDL").val();
        if (HtmlTypeDDV == 1) {
            $("#ContentId").show();
            $("#TextAreaId").hide();
            $("#HtmlEditorId").parent().hide();
            $("#FileUploadId").hide();

        }
        if (HtmlTypeDDV == 2) {
            $("#ContentId").hide();
            $("#HtmlEditorId").parent().hide();
            $("#FileUploadId").hide();
            $("#TextAreaId").show();
            $("#ContentId").val($("#TextAreaId").val());
        }
        if (HtmlTypeDDV == 3) {
            tinymce.init({ selector: 'textarea#HtmlEditorId' });
            $("#ContentId").hide();
            $("#TextAreaId").hide();
            $("#FileUploadId").hide();
            $("#HtmlEditorId").parent().show();

            //tinymce.init({ selector: 'textarea' });

        }
        if (HtmlTypeDDV == 4) {
            $("#ContentId").hide();
            $("#TextAreaId").hide();
            $("#HtmlEditorId").parent().hide();
            $("#FileUploadId").show();
        }

    }

    </script>

LandingPage/Areas/Admin/Views/CMS/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2 class="page-title">Index</h2>

<a href="@Url.Action("Create","CMS")"> Adauga item </a>


<link href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
<div class="datatable">
    <table id="datatable" class="display" style="width:100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>MenuItemId</th>
                <th>HtmlType</th>
                <th>Content</th>
                <th>Delete</th>
                <th>Edit</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>MenuItemId</th>
                <th>HtmlType</th>
                <th>Content</th>
                <th>Delete</th>
                <th>Edit</th>
            </tr>
        </tbody>
    </table>
</div>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js" type="text/javascript"></script>

<script type="text/javascript">

    function reload() {
        $('#datatable').DataTable({
            ajax: "@Url.Action("GetAll","CMS")",
            columns: [
                { data: "id" },
                { data: "name" },
                { data: "menuItemId" },
                { data: "htmlType" },
                { data: "content"},
                {
                    data: "id", render: function (data, type, row, meta) {
                        data = '<input value="Stergere" type="Button" onclick="deleteItem(\'' + data + '\')" />';

                        return data;
                    }
                },
                {
                    data: "id", render: function (data, type, row, meta) {
                        var link = '/admin/cms/createItem?id=' + data;
                        data = '<a href="' + link + '">Edit</a>';
                        return data;
                    }
                }
            ]
        });
    }
    
     function deleteItem(data) {
        $.ajax({
            url: '@Url.Action("DeleteItem","CMS")',
            data: { ItemId: data}
        }).success(function (response) {
            if (response == true) {
                $('#datatable').DataTable().ajax.reload();
            }
            else { alert("Nu s-a putut sterge itemul");}

        })

    }

    $(document).ready(function () {
        reload();
        var table = $('#datatable').DataTable();
        $('#datatable tbody').on('dblclick', 'tr', function () {
            var data = table.row(this).data();
            console.log(data.id);
            window.location = "/admin/cmsdetails?cmsId=" + data.id;
        });
    });



</script>