LandingPage/Models/ScriptsViewModels/ScriptsViewModels.cs
using DBModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;


namespace LandingPage.Models.ScriptsViewModels
{
    public class ScriptsViewModels
    {
        [Display(Name="Id")]
        public int Id { get; set; }
        [Display(Name = "Name")]
        public string Name { get; set; }
        [Display(Name = "Script")]
        public string Script { get; set; }
        [Display(Name = "Header")]
        public bool Header { get; set; }
        [Display(Name = "Footer")]
        public bool Footer { get; set; }

        public static explicit operator ScriptsViewModels(Scripts model)
        {
            return new ScriptsViewModels
            {
                Id = model.Id,
                Name = model.Name,
                Script = model.Script,
                Header = model.Header,
                Footer = model.Footer

            };
        }

        public Scripts TransformScriptsVM(ScriptsViewModels model)
        {
            return new Scripts
            {
                Id = model.Id,
                Name = model.Name,
                Script = model.Script,
                Header = model.Header,
                Footer = model.Footer
            };
        }
    }
}

LandingPage/Areas/Admin/Controllers/ScriptsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LandingPage.Models.ScriptsViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Service;

namespace LandingPage.Areas.Admin.Controllers
{
    [Area("admin")]
    [Authorize]
    public class ScriptsController : Controller
    {
        [Route("admin/scripts/getall")]
        public JsonResult GetAll()
        {
            var _repo = new ScriptsManager();
            return Json(new { data = _repo.GetAll() });
        }

        [Route("admin/scripts/deleteScript")]
        public JsonResult Delete(int id)
        {
            var _repo = new ScriptsManager();
            var script = _repo.GetById(id);
            if (script.Id > 0)
            {
                _repo.Delete(script.Id);
                return Json(true);
            }
            else return Json(false);
        }

        [Route("admin/scripts/createScript")]
        [HttpPost]
        public IActionResult Create(ScriptsViewModels model)
        {
            if (ModelState.IsValid)
            {
                if (model.Id > 0)
                    new ScriptsManager().Update(new ScriptsViewModels().TransformScriptsVM(model));
                else
                    new ScriptsManager().Create(new ScriptsViewModels().TransformScriptsVM(model));
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [Route("admin/scripts/createScript")]
        [HttpGet]
        public IActionResult Create(int id)
        {
            var viewModel = new ScriptsViewModels();
            if (id > 0)
            {
                viewModel = (ScriptsViewModels)(new ScriptsManager().GetById(id));
            }

            return View(viewModel);

        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

LandingPage/Areas/Admin/Views/Scripts/Create.cshtml
@model LandingPage.Models.ScriptsViewModels.ScriptsViewModels

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<br />
<h2>Creare</h2>

<h4>ScriptsViewModels</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create"> 
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="Id" />
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Script" class="control-label"></label>
                <textarea asp-for="Script" class="form-control" rows="10"></textarea>
                <span asp-validation-for="Script" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Header" /> @Html.DisplayNameFor(model => model.Header)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Footer" /> @Html.DisplayNameFor(model => model.Footer)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts{
<script src="~/js/jquery.js"></script>
}

LandingPage/Areas/Admin/Views/Scripts/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2 class="page-title">Index</h2>

<a href="@Url.Action("Create","Scripts")"> Adauga item </a>

<link href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
<div class="datatable">
    <table id="datatable" class="display" style="width:100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Script</th>
                <th>Header</th>
                <th>Footer</th>
                <th>Delete</th>
                <th>Edit</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Script</th>
                <th>Header</th>
                <th>Footer</th>
                <th>Delete</th>
                <th>Edit</th>
            </tr>
        </tbody>
    </table>
</div>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js" type="text/javascript"></script>

<script type="text/javascript">

    function reload() {
        $('#datatable').DataTable({
            ajax: "@Url.Action("GetAll","Scripts")",
            columns: [
                { data: "id" },
                { data: "name" },
                { data: "script" },
                { data: "header" },
                { data: "footer"},
                {
                    data: "id", render: function (data, type, row, meta) {
                        data = '<input value="Stergere" type="Button" onclick="deleteItem(\'' + data + '\')" />';
                        return data;
                    }
                },
                {
                    data: "id", render: function (data, type, row, meta) {
                        var link = '/admin/scripts/createScript?id=' + data;
                        data = '<a href="' + link + '">Edit</a>';
                        return data;
                    }
                }
            ]
        });
    }

     function deleteItem(data) {
        $.ajax({
            url: '@Url.Action("deleteScript","Scripts")',
            data: { Id: data}
        }).success(function (response) {
            if (response == true) {
                $('#datatable').DataTable().ajax.reload();
            }
            else { alert("Nu s-a putut sterge itemul");}

        })

    }

    $(document).ready(function () {
        reload();
    });
</script>