LandingPage/Models/HtmlTypesViewModels/HtmlTypesViewModels.cs
using DBModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LandingPage.Models.HtmlTypesViewModels
{
    public class HtmlTypesViewModels
    {
        [Display(Name="Id")]
        public int Id { get; set; }
        [Display(Name="Nume")]
        public String Name { get; set; }

        public static explicit operator HtmlTypesViewModels(HtmlTypes model)
        {
            return new HtmlTypesViewModels
            {
                Id = model.Id,
                Name = model.Name
            };

        }

        public HtmlTypes Transform(HtmlTypesViewModels model)
        {
            return new HtmlTypes
            {
                Id = model.Id,
                Name = model.Name
            };
        }
    }
}

LandingPage/Areas/Admin/Controllers/HtmlTypesController.cs
using LandingPage.Models.HtmlTypesViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Service;

namespace LandingPage.Areas.Admin.Controllers
{
    [Area("admin")]
    [Authorize]
    public class HtmlTypesController : Controller
    {   [Route("admin/HtmlTypes/getall")]
        public JsonResult GetAll()
        {
            var _repo = new HtmlTypesManager();
            return Json(new { data = _repo.GetAll() });
        }

        [Route("admin/HtmlTypes/deleteType")]
        public JsonResult Delete(int id)
        {
            var _repo = new HtmlTypesManager();
            var item = _repo.GetById(id);
            if (item.Id > 0)
            {
                _repo.Delete(item.Id);
                return Json(true);
            }
            else return Json(false);
        }

        public IActionResult Index()
        {
            return View();
        }

        [Route("admin/HtmlTypes/createType")]
        [HttpGet]
        public IActionResult Create(int id)
        {
            var viewModel = new HtmlTypesViewModels();
            if (id > 0)
            {
                viewModel = (HtmlTypesViewModels)(new HtmlTypesManager().GetById(id));
            }

            return View(viewModel);

        }
        [Route("admin/HtmlTypes/createType")]
        [HttpPost]
        public IActionResult Create(HtmlTypesViewModels htmlType)
        {
            
            if (ModelState.IsValid)
            {
                if (htmlType.Id > 0)

                    new HtmlTypesManager().Update(new HtmlTypesViewModels().Transform(htmlType));
                else
                    new HtmlTypesManager().Create(new HtmlTypesViewModels().Transform(htmlType));

                return RedirectToAction("Index");
            }
            return View(htmlType);
        }
    }
}

LandingPage/Areas/Admin/Views/HtmlTypes/Create.cshtml
@model LandingPage.Models.HtmlTypesViewModels.HtmlTypesViewModels

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>HtmlTypesViewModels</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LandingPage/Areas/Admin/Views/HtmlTypes/Index.cshtml
@model IEnumerable<LandingPage.Models.HtmlTypesViewModels.HtmlTypesViewModels>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<h2 class="page-title">Index</h2>

<a href="@Url.Action("Create","HtmlTypes")"> Adauga type </a>


<link href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
<div class="datatable">
    <table id="datatable" class="display" style="width:100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Delete</th>
                <th>Edit</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Delete</th>
                <th>Edit</th>
            </tr>
        </tbody>
    </table>
</div>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js" type="text/javascript"></script>

<script>
    function reload() {
        $("#datatable").DataTable({
            ajax: "@Url.Action("GetAll","HtmlTypes")",
            columns:
                [
                    { data: "id" },
                    { data: "name" },
                    {
                        data: "id", render: function (data, type, row, meta) {
                            data = '<input value="Stergere" type="Button" onclick="deleteType(\'' + data + '\')" />';
                            return data;
                        }
                    },
                    {
                        data: "id", render: function (data, type, row, meta) {
                            var link = '/admin/htmltypes/createType?id=' + data;
                            data = '<a href="' + link + '">Edit</a>';
                            return data;
                        }
                    }
                ]
        })
    }

    function deleteType(data) {
        $.ajax({
            url: '@Url.Action("deleteType","HtmlTypes")',
            data: { Id: data}
        }).success(function (response) {
            if (response == true) {
                $('#datatable').DataTable().ajax.reload();    
            }
            else { alert("Nu s-a putut sterge tipul");}

        })

    }

    $(document).ready(function () {
        reload();
    });
</script>