LandingPage/Models/CMSDetailsViewModels.cs
using DBModels;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LandingPage.Models.CMSDetailsViewModels
{
    public class CMSDetailsViewModels
    {
        [Display(Name = "Id")]
        public int Id { get; set; }
        [Display(Name = "CMSId")]
        public int CMSId { get; set; }
        [Display(Name = "Nume")]
        public String Name { get; set; }
        [Display(Name = "Index")]
        public int OrderIndex { get; set; }
        [Display(Name = "Tip HTML")]
        public int HtmlTypeId { get; set; }
        [Display(Name = "Continut")]
        public String Content { get; set; }
        public IFormFile FileUploadId { get; set; }
        public String ContentId { get; set; }
        public String TextAreaId { get; set; }
        public String HtmlEditorId { get; set; }



        public static explicit operator CMSDetailsViewModels(CMSDetails model)
        {
            return new CMSDetailsViewModels
            {
                Id = model.Id,
                CMSId = model.CMSId,
                Name = model.Name,
                OrderIndex = model.OrderIndex,
                HtmlTypeId = model.HtmlTypeId,
                Content = model.Content,
                ContentId = model.Content,
                TextAreaId = model.Content,
                HtmlEditorId = model.Content

            };

        }

        public CMSDetails Transform(CMSDetailsViewModels model)
        {
            return new CMSDetails
            {
                Id = model.Id,
                CMSId=model.CMSId,
                Name = model.Name,
                OrderIndex = model.OrderIndex,
                HtmlTypeId = model.HtmlTypeId,
                Content = model.Content
            };
        }
    }
}

LandingPage/Areas/Admin/Controllers/CMSDetailsController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LandingPage.Models.CMSDetailsViewModels;
using Service;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using System.Collections.Generic;

namespace LandingPage.Areas.Admin.Controllers
{
    [Area("admin")]
    [Authorize]
    public class CMSDetailsController : Controller
    {
        private IHostingEnvironment _hostingEnvironment;

        public CMSDetailsController(IHostingEnvironment emv)
        {
            _hostingEnvironment = emv;
        }

        [Route("admin/cmsdetails/getall")]
        public JsonResult GetAll(int cmsId)
        {
            var all = new List<DBModels.CMSDetails>();
            if (cmsId == 0)
            { all = new CMSDetailsManager().GetAll(); }
            else
            {
                all = new CMSDetailsManager().GetByCMSId(cmsId);
            }
            return Json(new { data = all });
        }
        [Route("admin/cmsdetails")]
        public IActionResult Index(int cmsId)
        {
            var all = new List<DBModels.CMSDetails>();
            if (cmsId == 0)
            {  all = new CMSDetailsManager().GetAll(); }
            else
            {
                all = new CMSDetailsManager().GetByCMSId(cmsId);
            }
            ViewBag.cmsId = cmsId;
            return View(all);
        }



        [Route("admin/cmsdetails/deleteItem")]
        public JsonResult DeleteItem(int ItemId)
        {
            var _cmsDetailsItemManager = new CMSDetailsManager();
            var item = _cmsDetailsItemManager.GetById(ItemId);
            if (item.Id > 0)
            {
                _cmsDetailsItemManager.Delete(ItemId);

                return Json(true);
            }
            else
                return Json(false);
        }

        [Route("admin/cmsdetails/createItem")]
        [HttpGet]
        public IActionResult Create(int id)

        {
            ViewBag.CMSId = new SelectList(new CMSManager().GetAll(), "Id", "Name");
            ViewBag.HtmlTypeId = new SelectList(new HtmlTypesManager().GetAll(), "Id", "Name");

            var viewModel = new CMSDetailsViewModels();
            if (id > 0)
            {
                viewModel = (CMSDetailsViewModels)(new CMSDetailsManager().GetById(id));
            }

            return View(viewModel);

        }

        [Route("admin/cmsdetails/createItem")]
        [HttpPost]
        public async Task<IActionResult> Create(CMSDetailsViewModels item, IFormFile FileUploadId)
        {
            var content = "";
            if (item.HtmlTypeId == 1)
            {
                content = item.ContentId;
            }
            else
                if (item.HtmlTypeId == 2)
            {
                content = item.TextAreaId;
            }
            else

                if (item.HtmlTypeId == 3)
            {
                content = item.HtmlEditorId;
            }
            else
            {
                if (item.FileUploadId != null)
                {
                    var filename = item.FileUploadId.FileName;
                    var path = Path.Combine(_hostingEnvironment.WebRootPath + "\\siteimages", filename);
                    var relpath = "/siteimages/" + filename;

                    content = relpath;
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await item.FileUploadId.CopyToAsync(stream);
                    }
                }
            }
            ViewBag.CMSId = new SelectList(new CMSManager().GetAll(), "Id", "Name");
            ViewBag.HtmlTypeId = new SelectList(new HtmlTypesManager().GetAll(), "Id", "Name");
            item.Content = content;


            if (ModelState.IsValid)
            {
                if (item.Id > 0)
                {
                    if (string.IsNullOrWhiteSpace(item.Content))
                    {
                        var oldItem = new CMSDetailsManager().GetById(item.Id);
                        item.Content = oldItem.Content;
                    }
                    new CMSDetailsManager().Update(new CMSDetailsViewModels().Transform(item));
                }
                else
                    new CMSDetailsManager().Create(new CMSDetailsViewModels().Transform(item));

                return RedirectToAction("Index");
            }
            return View(item);
        }
    }
}

LandingPage/Areas/Admin/Views/CMSDetails/Create.cshtml
@model LandingPage.Models.CMSDetailsViewModels.CMSDetailsViewModels

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var title = Model.Id > 0 ? "Editare" : "Creare";
}

<head>

    <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
</head>
<h2>Create</h2>

<h4>CMSDetailsViewModels</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data" asp-controller="CMSDetails">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            @*<div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="CMSId" class="control-label"></label>
                <select asp-for="CMSId" class="form-control" asp-items="ViewBag.CMSId"></select>
                <span asp-validation-for="CMSId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderIndex" class="control-label"></label>
                <input asp-for="OrderIndex" class="form-control" />
                <span asp-validation-for="OrderIndex" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HtmlTypeId" class="control-label"></label>
                <select asp-for="HtmlTypeId" class="form-control" id="HtmlTypeDDL" asp-items="ViewBag.HtmlTypeId"></select>
                <span asp-validation-for="HtmlTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" id="ContentId" name="ContentId" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <textarea rows="4" cols="50" id="TextAreaId" name="TextAreaId" asp-for="TextAreaId">
            </textarea>

            </div>
            <div class="form-group">
                <textarea id="HtmlEditorId" name="HtmlEditorId" asp-for="HtmlEditorId">
            </textarea>
            </div>
            <div class="form-group">
                <img width="200" src="@Model.Content" alt="">
                <input type="file" name="FileUploadId" id="FileUploadId" asp-for="FileUploadId" />
            </div>
            <div class="form-group">
                <input type="submit"  value="@title" class="btn btn-default" />
            </div>

        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script src="~/js/jquery.js"></script>

<script type="text/javascript">
$(document).ready(function () {


     CompleteValues();

    $("#HtmlTypeDDL").change(function () {
        CompleteValues();

            });


    });

    function CompleteValues() {
        var HtmlTypeDDV = $("#HtmlTypeDDL").val();
        if (HtmlTypeDDV == 1) {
            $("#ContentId").show();
            $("#TextAreaId").hide();
            $("#HtmlEditorId").parent().hide();
            $("#FileUploadId").hide();

        }
        if (HtmlTypeDDV == 2) {
            $("#ContentId").hide();
            $("#HtmlEditorId").parent().hide();
            $("#FileUploadId").hide();
            $("#TextAreaId").show();
            $("#ContentId").val($("#TextAreaId").val());
        }
        if (HtmlTypeDDV == 3) {
            tinymce.init({ selector: 'textarea#HtmlEditorId' });
            $("#ContentId").hide();
            $("#TextAreaId").hide();
            $("#FileUploadId").hide();
            $("#HtmlEditorId").parent().show();

            //tinymce.init({ selector: 'textarea' });

        }
        if (HtmlTypeDDV == 4) {
            $("#ContentId").hide();
            $("#TextAreaId").hide();
            $("#HtmlEditorId").parent().hide();
            $("#FileUploadId").show();
        }

    }

</script>

LandingPage/Areas/Admin/Views/CMSDetails/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2 class="page-title">Index</h2>

<a href="@Url.Action("Create","CMSDetails")"> Adauga item </a>


<link href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
<div class="datatable">
    <table id="datatable" class="display" style="width:100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>CMSId</th>
                <th>Name</th>
                <th>OrderIndex</th>
                <th>HtmlTypeId</th>
                <th>Content</th>
                <th>Delete</th>
                <th>Edit</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>Id</th>
                <th>CMSId</th>
                <th>Name</th>
                <th>OrderIndex</th>
                <th>HtmlTypeId</th>
                <th>Content</th>
                <th>Delete</th>
                <th>Edit</th>
            </tr>
        </tbody>
    </table>
</div>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js" type="text/javascript"></script>

<script type="text/javascript">

    function reload() {
        $('#datatable').DataTable({
            ajax: "@Url.Action("GetAll","CMSDetails",new { cmsId = ViewBag.cmsId })",
            columns: [
                { data: "id" },
                {data: "cmsId"},
                { data: "name" },
                { data: "orderIndex" },
                { data: "htmlTypeId" },
                { data: "content"},
                {
                    data: "id", render: function (data, type, row, meta) {
                        data = '<input value="Stergere" type="Button" onclick="deleteItem(\'' + data + '\')" />';

                        return data;
                    }
                },
                {
                    data: "id", render: function (data, type, row, meta) {
                        var link = '/admin/cmsdetails/createItem?id=' + data;
                        data = '<a href="' + link + '">Edit</a>';
                        return data;
                    }
                }
            ]
        });
    }

     function deleteItem(data) {
        $.ajax({
            url: '@Url.Action("DeleteItem","CMSDetails")',
            data: { ItemId: data}
        }).success(function (response) {
            if (response == true) {
                $('#datatable').DataTable().ajax.reload();
            }
            else { alert("Nu s-a putut sterge itemul");}

        })

    }

    $(document).ready(function () {
        reload();
    });



</script>